Services
CrazyTapok/TaskManager pull request #5
Opened 2024-12-11 05:45 UTC by CrazyTapok

1. Screenshot: 
![image](https://github.com/user-attachments/assets/d2ba12b0-2a51-4be2-a04a-abc2e5eaa589)

2. What has been implemented:
  - [x] Add generic service 
  - [x] Add service for each entity 
  - [x] Add interface for services 
  - [x] Fix the links between entities 
  - [x] Add IsDeleted propery in models 
  - [x] Change method DeleteAsync in Repository
  - [x] Change method DeleteEntity in RepositoryTest
  - [x] Change configuration 
  - [x] Create new migration 
  - [x] Add repositories for each entity 
  - [x] Add new tests.

2024-12-13 10:05 UTC, svirzhevskiy requested changes

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.API/TaskManager.API.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
пошла жара?) Может тогда вообще на .net 9 обновить?)

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Infrastructure/ServiceCollection.cs
> +        services.AddTransient <ITaskService, TaskService>();
```suggestion
        services.AddTransient<ITaskService, TaskService>();
```

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Interfaces/Data/IProjectRepository.cs
> +    Task<IEnumerable<Project>> FindAsync(Expression<Func<Project, bool>> predicate, CancellationToken cancellationToken);
почему везде одинаковый FindAsync? его же можно в дженерик переместить

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Interfaces/Data/IRepository.cs
> +    Task<List<TModel>> GetAllAsync(CancellationToken cancellationToken);
CancellationToken часто делают необязательным параметром, но можно и так

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Interfaces/Services/ICompanyService.cs
> +internal interface ICompanyService : IService<Company>
вроде же не обязательно создавать пустой интерфейс. Просто пользуешься дженериком везде

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Models/Company.cs
> +    public bool IsDeleted { get; set; }
бля, вот это конечно не оч красиво выходит. Такое проперти хочется держать только в модели для базы и не видеть в моделях кора. Номы этим жертвуем :(

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/CompanyService.cs
> +public class CompanyService : ICompanyService
делай базовую реализацию дженерика с общими методами и наследуйся от нее в сервисах для конкретной модели. Много дублирования кода уберешь. У тебя все эти сервисы почти идентичны, за исключением модели. Дженерик же может быть не только интерфейс, но и реализация

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/CompanyService.cs
> +        return await _companyRepository.GetAllAsync(cancellationToken);
await тут не обязателен, можно просто таску возвращать

2024-12-13 10:05 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/CompanyService.cs
> +            throw new ValidationException($"Entity with id {id} not found", "");
это не ValidationException а какой-нибудь not found

2024-12-24 05:53 UTC, CrazyTapok commented on src/TaskManager.API/TaskManager.API.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
+

2024-12-24 19:12 UTC, svirzhevskiy requested changes

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +    }
```suggestion
    public Task<List<TModel>> FindAsync(Expression<Func<TModel, bool>> predicate, CancellationToken cancellationToken = default)
    {
        return _dbSet.Where(predicate).ToListAsync(cancellationToken);
    }
```

Я это имелл ввиду, когда писал про ctoken :) Налабл его делать не нужно. Вообще стремимся избегать налов в коде

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +            typeof(TModel).GetProperty("IsDeleted")?.SetValue(entity, true);
рефлексия бьет по перформансу всегда, старайся ее избегать.
Чтобы решить вопрос здесь, нужно создать базовый класс, который будет содержать общие свойства для всех моделей и использовать его в дженериках

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +        return _dbSet.FindAsync(id, cancellationToken ?? CancellationToken.None).AsTask();
почему здесь избегаешь ValueTask?
Почитай чем отличается от обычной и заиспользуй

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/TaskRepository.cs
> +internal class TaskRepository : Repository<Task>
Ответ на твой вопрос по FindAsync: Если есть специфик серфис, то и интерфейс для него свой фигач, иначе ты реально их не отличишь потом в DI

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/ProjectRepository.cs
> +internal class ProjectRepository : Repository<Project>
В каком-то там дотнете добавили primary constructor. Мне нравится использовать их в небольших классах
https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors#dependency-injection

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/ProjectRepository.cs
> +    public async Task<IEnumerable<Project>> FindAsync(Expression<Func<Project, bool>> predicate, CancellationToken? cancellationToken)
Ты везде IEnumerable как возвращаемое значение поставил, чтобы потом все равно кастить в лист? 😁
![image](https://github.com/user-attachments/assets/3413fafb-be45-45fa-82bd-9f1f917eaec6)
Поставь лист и не парься. И сможешь возвращать таску, а не эвейтить тут

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/TaskRepository.cs
> +internal class TaskRepository : Repository<Task>
при этом в сервисах ты почему-то это сделал(～￣▽￣)～

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Core/Infrastructure/ServiceCollection.cs
> +public static class ServiceCollection
```suggestion
public static class ServiceCollectionExtensions
```

2024-12-24 19:12 UTC, svirzhevskiy commented on src/TaskManager.Core/Infrastructure/ServiceCollection.cs
> +        services.AddTransient(typeof(IService<Company>), typeof(Service<Company>));
```suggestion
        services.AddTransient<IService<Company>, Service<Company>>(); 
```

2024-12-24 19:16 UTC, svirzhevskiy commented on src/TaskManager.Core/Infrastructure/ServiceCollection.cs
> +        services.AddTransient<ITaskService, TaskService>();
почему транзиент? я бы скоупд по дефолту делал

2024-12-25 07:43 UTC, CrazyTapok commented on src/TaskManager.Infrastructure/Repositories/ProjectRepository.cs
> +internal class ProjectRepository : Repository<Project>
это можно применить ко всем классам сервисов и репозиториям?

2025-01-05 15:51 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +    }
и все таки почему ты не хочешь использовать CancellationToken cancellationToken = default?🤔
Это, конечно, дело вкуса, но дает возможность не использовать его там, где его нет и выглядит красивей

2025-01-05 16:02 UTC, svirzhevskiy requested changes

2025-01-05 16:02 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +    public ValueTask<TModel> GetByIdAsync(Guid id, CancellationToken cancellationToken)
```suggestion
    public ValueTask<TModel?> GetByIdAsync(Guid id, CancellationToken cancellationToken)
```

2025-01-05 16:02 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +            await context.SaveChangesAsync();
```suggestion
            await context.SaveChangesAsync(cancellationToken); 
```

2025-01-05 16:02 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/Service.cs
> +            throw new NotFoundException($"Entity with id {id} not found", "");
не вкуриваю кастомный эксепшн. Ты сделал свой NotFoundException со свойством Property, которое заполняешь пустой строкой?

2025-01-05 16:04 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/EmployeeService.cs
> +public class EmployeeService : Service<Employee>, IEmployeeService
для чего имплементации сервисов публичные? не выходит сделать интернал?

2025-01-05 16:09 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/EmployeeService.cs
> +        return _employeeRepository.FindAsync(t => t.Projects.Any(t => t.Id == projectId), cancellationToken);
косметический коммент чисто от меня: мне не нравится, когда в лямбдах позволяют себе называть переменные отпизды🥲 Почему переменные не в люмбдах нормально называем, а в них можно просто букву поставить? Могу еще принять, когда в цепочке только одна лямюда и буква это эта хотя бы первая из реального названия, но все равно хуйня, по-моему. 
Имхо не сложно написать целое слово. Что здесь значит t? Почему t? Почему две разных переменных, одна означает employee, а другая project и обе называются t, что перекрывает друг друга?
```suggestion
        return _employeeRepository.FindAsync(employee => employee.Projects.Any(project => project.Id == projectId), cancellationToken); 
```

2025-01-05 16:09 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/EmployeeService.cs
> +
```suggestion
```

2025-01-05 16:12 UTC, svirzhevskiy commented on src/TaskManager.Core/Models/Task.cs
>      public Guid CreateEmployeeId { get; set; }
С точки зрения англа, конечно, лучше CreatedBy и employee можно убрать, если у тебя все эмплои :)
```suggestion
    public Guid CreatedById { get; set; }
```

2025-01-05 16:13 UTC, svirzhevskiy commented on src/TaskManager.Core/Models/Task.cs
>      public Guid CreateEmployeeId { get; set; }
необязательный коммент*

2025-01-05 16:14 UTC, svirzhevskiy commented on src/TaskManager.Infrastructure/EF/DBContext.cs
> +        //Database.EnsureCreated();
можно это как-то поправить? Чтобы оно выполняло скрипты, только когда нужно. Например, когда базы нет

2025-01-05 16:19 UTC, svirzhevskiy commented
заглянул в тесты, а ты их тоже от пизды херачишь, не годиться

2025-01-05 16:21 UTC, svirzhevskiy commented on src/TaskManager.Tests/Core/Services/EmployeeServiceTests.cs
> +                new Employee { Id = Guid.NewGuid(), Name = "Employee1", Projects = new List<Project> { new Project { Id = projectId } } },
```suggestion
                _fixture.Build<Employee>().With(employee => employee.Projects, [_fixture.Build<Project>().With(project => project.Id, projectId).Create()]).Create(),
```

2025-01-05 16:22 UTC, svirzhevskiy commented on src/TaskManager.Tests/Core/Services/EmployeeServiceTests.cs
> +                });
```suggestion
            _mockRepo.Setup(repo => repo.FindAsync(It.IsAny<Expression<Func<Employee, bool>>>(), _cancellationToken))
                .ReturnsAsync((Expression<Func<Employee, bool>> predicate, CancellationToken _) =>
                    employees.Where(predicate.Compile()).ToList());
```

2025-01-05 16:23 UTC, svirzhevskiy commented on src/TaskManager.Tests/Core/Services/EmployeeServiceTests.cs
> +            Assert.All(result, employee => Assert.Contains(employee, employees));
```suggestion
           //Arrange
            var companyId = Guid.NewGuid(); 
            var employees = new List<Employee> 
            { 
                new Employee { Id = Guid.NewGuid(), Name = "Employee1", CompanyId = companyId }, 
                new Employee { Id = Guid.NewGuid(), Name = "Employee2", CompanyId = companyId }, 
                new Employee { Id = Guid.NewGuid(), Name = "Employee3", CompanyId = Guid.NewGuid() } 
            }; 
            
            _mockRepo.Setup(repo => repo.FindAsync(It.IsAny<Expression<Func<Employee, bool>>>(), _cancellationToken))
                .ReturnsAsync((Expression<Func<Employee, bool>> predicate, CancellationToken token) => 
                { 
                    return employees.Where(predicate.Compile()).ToList(); 
                }); 
            
            //Act
            var result = await _service.GetEmployeesByCompanyIdAsync(companyId, _cancellationToken); 
            
            //Assert
            Assert.Equal(2, result.Count); 
            Assert.All(result, employee => Assert.Contains(employee, employees)); 
```
так в тестах для красоты пишут

2025-01-05 16:25 UTC, svirzhevskiy commented on src/TaskManager.Tests/Core/Services/ServiceTests.cs
> +    private readonly IService<TestModel> _service;
```suggestion
    private readonly Service<TestModel> _service;
```
тестим реализацию

2025-01-05 16:25 UTC, svirzhevskiy commented on src/TaskManager.Tests/Infrastructure/EF/TestDBContext.cs
> +        base.OnModelCreating(modelBuilder); }
```suggestion
        base.OnModelCreating(modelBuilder); 
   }
```

2025-01-05 16:26 UTC, svirzhevskiy commented on src/TaskManager.Tests/Infrastructure/Repositories/EmployeeRepositoryTests.cs
> +        Assert.Equal(matchingEmployees.Count, result.Count());
```suggestion
        Assert.Equal(matchingEmployees.Count, result.Count);
```

2025-01-05 16:27 UTC, svirzhevskiy commented on src/TaskManager.Tests/Infrastructure/Repositories/EmployeeRepositoryTests.cs
> +        Expression<Func<Employee, bool>> predicate = t => t.Name.Contains("BestEmployee");
"BestEmployee" выносим в константу, тк используешь потом для проверки

2025-01-05 16:27 UTC, svirzhevskiy commented on src/TaskManager.Tests/Infrastructure/Repositories/RepositoryTests.cs
>      private readonly IRepository<TestModel> _repository;
```suggestion
    private readonly Repository<TestModel> _repository;
```

2025-01-05 16:30 UTC, svirzhevskiy commented
на каждой мелочи останавливаемся, но это в воспитательных целях😊

2025-01-05 16:33 UTC, svirzhevskiy commented
сообщения коммитов, кстати, нравятся

2025-01-08 14:58 UTC, CrazyTapok commented on src/TaskManager.Core/Services/EmployeeService.cs
> +public class EmployeeService : Service<Employee>, IEmployeeService
выходит

2025-01-08 14:58 UTC, CrazyTapok commented on src/TaskManager.Core/Services/Service.cs
> +            throw new NotFoundException($"Entity with id {id} not found", "");
Да, пока не знаю что туда передавать

2025-01-08 15:02 UTC, CrazyTapok commented on src/TaskManager.Core/Services/EmployeeService.cs
> +
случайный коммент?

2025-01-08 16:23 UTC, CrazyTapok commented on src/TaskManager.Infrastructure/EF/DBContext.cs
> +        //Database.EnsureCreated();
дума можно

2025-01-08 16:25 UTC, CrazyTapok commented on src/TaskManager.Infrastructure/Repositories/Repository.cs
> +    }
я просто не знал про такое

2025-01-09 07:20 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/Service.cs
> +            throw new NotFoundException($"Entity with id {id} not found", "");
то есть ты это заложил сам не знаешь для чего? мб удалить тогда?

2025-01-09 07:21 UTC, svirzhevskiy commented on src/TaskManager.Core/Services/EmployeeService.cs
> +
пустая строка лишняя. Не случайный

2025-01-09 07:24 UTC, CrazyTapok commented on src/TaskManager.Core/Services/Service.cs
> +            throw new NotFoundException($"Entity with id {id} not found", "");
Удалить property или сам класс?

2025-01-09 08:03 UTC, svirzhevskiy approved these changes

2025-01-09 08:17 UTC, merged